server:
  servlet:
    context-path: /boot
  port: 8000

#数据眼
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/et1910?serverTimezone=GMT
    username: root
    password: etoak
    hikari:
      maximum-pool-size: 50
  #thymeleaf
  thymeleaf:
    cache: false
    encoding: UTF-8
  #限制图片大小 默认1mb
  servlet:
    multipart:2MB

#mybatis
mybatis:
  type-aliases-package: com.etoak.bean
  mapper-locations: classpath:/mappers/*.xml

#pagehelper
pagehelper:
  reasonable: true

#开启打印sql  主动只喝了logging
logging:
  level:
    com.etoak.mapper: debug

#文件上传配置
#<mvc:resources location="file:d:/upload" mapping="/pics/**"
upload:
  dir: d:/upload/
  savePathPrefix: /pics/
  mapping: /pics/**
