server:
  servlet:
    context-path: /boot
  port: 8000

#数据眼
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/et1910?serverTimezone=GMT
    username: root
    password: etoak
    hikari:
      maximum-pool-size: 50
  #thymeleaf
  thymeleaf:
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      # 默认1MB
      max-file-size: 2MB

#mybatis
mybatis:
  type-aliases-package: com.etoak.bean
  mapper-locations: classpath:/mappers/*.xml

#pagehelper
pagehelper:
  reasonable: true

#开启打印sql  主动只喝了logging
logging:
  level:
    com.etoak.mapper: debug

# 自定义配置：文件上传和图片访问配置
upload:
  dir: d:/upload/
  savePathPrefix: /pics/
  mapping: /pics/**